### ISSUE TITLE
LED Examples

### ISSUE THREAD

**Issue by shawnsparks** [WasabiFan/ev3dev-lang-js#2]
I pulled down ev3dev 0.9.2 today. I tried to run the test-battery-led.js file, but it has errors. ev3dev.LED.redLeft is undefined. It appears ev3dev.LED has no properties. If I run new ev3dev.LED( 'ev3-left0:red:ev3dev' ); I'm able to use brightness and maxBrightness properties. It feels like I can use LED as a class, but none of the static properties carry over to bin/index.js.

**Comment by WasabiFan** [comment]
I haven't gotten a chance to fix the LED demo after we made some large changes to those LED properties, so I am not surprised that it doesn't work at the moment. I'll take a look when I get the chance and post back when I figure it out (probably within a day).

**Comment by WasabiFan** [comment]
@marshmellow1328 What version of ev3dev are you running? I am able to run the `test-battery-led.js` script on my ev3 without errors, and it's running  `Linux ev3dev 3.16.7-ckt14-6-ev3dev-ev3 #1 PREEMPT Wed Jul 8 14:08:29 CDT 2015 armv5tejl GNU/Linux`.

Are you running this from a clone of the repo, or an npm module? If you are running this from a clone of the repo, is it possible that you didn't run another build (`grunt tsc`) after pulling recent changes? If you are running it from npm, I suspect that that isn't recent enough to support recent kernels (so you should clone and build from source instead for now).

**Comment by shawnsparks** [comment]
I am running from npm: version 0.9.2. If there were tags on the repo, I would have looked at the examples from the version pulled from npm.

Sorry on the slow response. Saw the notification, but then forgot about it by the time I had a chance to get to it.

**Comment by WasabiFan** [comment]
> I am running from npm: version 0.9.2. If there were tags on the repo, I would have looked at the examples from the version pulled from npm.

Yeah, sorry about that... I have been having significant trouble getting time to update the library and publish new releases. I still have 2 or 3 major features to add/changes to make before it's in sync with the core ev3dev repo and ev3dev-lang, and haven't gone back to see how far I've diverged since the last release. Since I know that you are depending on my code, I'll push this to the top of my to-do list, so you can expect a new release within a week assuming all goes well.

> Sorry on the slow response. Saw the notification, but then forgot about it by the time I had a chance to get to it.

No problem! If you have any questions, feature requests, or other suggestions, I'm here to help.

**Comment by shawnsparks** [comment]
I'm just dabbling so no worries. Let me know if there's something I can do to help.

**Comment by WasabiFan** [comment]
Whoops... looks like I forgot to come back to this :wink: A fix for this was made and released a very long time ago.
