### ISSUE TITLE
slow startup time

### ISSUE THREAD

**Issue by joshrtay** [WasabiFan/ev3dev-lang-js#7]
We are experiencing startup times of nearly 10seconds for node processes. Is anyone else experiencing similar startup times?

**Comment by WasabiFan** [comment]
I recall having it take a second or two, but 10 would indicate that there is something else taking up the majority of your cpu cycles. Through an SSH session, can you run `top` to see what's using the CPU and RAM?

P.S. Maybe @dlech has some thoughts?

**Comment by dlech** [comment]
Pasting the output of `top` here sounds like a good place to start.

**Comment by WasabiFan** [comment]
After looking at this more closely, I think that this is honestly the time it takes to start Node on the EV3. It's unfortunate, but I guess it's the reality of the hardware that we're working with :cry:...

**Comment by dlech** [comment]
You can turn off some services to free up some RAM to see if it makes a difference.

```
sudo systemctl stop nmbd
sudo systemctl stop avahi-daemon
sudo systemctl stop systemd-journald
```

**Comment by dlech** [comment]
Python takes a long time to startup too, so it might not get much better.

**Comment by joshrtay** [comment]
We'll give that a go. CPU usage is an issue for us as well. Fluctuates between 30% and 80 %.

Are you guys using ev3dev with brickpi or something? The ev3 just doesn't seem to be able to handle it.

**Comment by WasabiFan** [comment]
Personally, I use ev3dev on an EV3, and I think it works pretty well. I think most ev3dev users do the same. Yes, it's a bit slow, but overall I haven't seen it as a big issue; and you get a lot of extra capability by using ev3dev instead of the stock kernel.

Internally, LEGO's implementation also runs a version of Linux, so there isn't much of a performance difference; you just notice it more when you are trying to do more advanced things.

If you're having performance problems, open an issue on the main ev3dev repo so it can be discussed. I'm sure others see similar slowness, and they might have extra ideas to contribute.

> Fluctuates between 30% and 80 %.

When? In standby, or while running code?
